"""add user's comment recived

Revision ID: 01574e99c1f8
Revises: a5217ad041ff
Create Date: 2020-01-09 14:27:21.126413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01574e99c1f8'
down_revision = 'a5217ad041ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_recived_comments_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_recived_comments_read_time')
    # ### end Alembic commands ###
