"""add other notification

Revision ID: 200d8c189f0d
Revises: 17cc8b8ecac1
Create Date: 2020-01-21 16:22:23.325240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200d8c189f0d'
down_revision = '17cc8b8ecac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_follows_read_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_likes_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_likes_read_time')
    op.drop_column('users', 'last_follows_read_time')
    # ### end Alembic commands ###
