"""fix bug

Revision ID: c4e755018022
Revises: 8437d3b1bde9
Create Date: 2020-01-03 15:27:55.481685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e755018022'
down_revision = '8437d3b1bde9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('mard_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mard_read', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
